### ISSUE TITLE
V8JsException: Array index exceeds maximum supported bound

### ISSUE THREAD

**Issue by raffis** [gyselroth/tubee#43]
#### Describe the bug
```
2019-06-05T07:11:36+00:00 DEBUG parse csv line [array{"Class":"Class","2105":"2355","0-LP":"W6m","68":"71","500":"13","NULL":"NULL","-10":"11"}]
2019-06-05T07:11:36+00:00 DEBUG process object [404] import for object [5cf76b28682f38001a6b7893] into data type [kzn::classes]
2019-06-05T07:11:36+00:00 DEBUG start workflow [kzn::classes::new-class-cn::create-update] [ensure=last] for the current object
2019-06-05T07:11:36+00:00 DEBUG no workflow condition set for workflow [kzn::classes::new-class-cn::create-update]
2019-06-05T07:11:36+00:00 ERROR failed import data object from source endpoint [kzn::classes::new-class-cn]
V8JsException: Array index exceeds maximum supported bound in /usr/share/tubee/src/lib/AttributeMap.php:78 stacktrace: #0 /usr/share/tubee/src/lib/Workflow/ImportWorkflow.php(70): Tubee\AttributeMap->map(Array, Object(MongoDB\BSON\UTCDateTime))
#1 /usr/share/tubee/src/lib/Async/Sync.php(372): Tubee\Workflow\ImportWorkflow->import(Object(Tubee\Collection), Array, Object(MongoDB\BSON\UTCDateTime), false)
#2 /usr/share/tubee/src/lib/Async/Sync.php(192): Tubee\Async\Sync->import(Object(Tubee\Collection), Array, Object(Generator), false, true)
#3 /usr/share/tubee/src/lib/Async/Sync.php(172): Tubee\Async\Sync->execute(Object(Tubee\Collection), Object(Tubee\Endpoint\Csv))
#4 /usr/share/tubee/src/lib/Async/Sync.php(140): Tubee\Async\Sync->loopEndpoints(Object(Tubee\Collection), Array, Array, Array)
#5 /usr/share/tubee/src/lib/Async/Sync.php(125): Tubee\Async\Sync->loopCollections(Array, Array)
#6 /usr/share/tubee/vendor/gyselroth/mongodb-php-task-scheduler/src/Worker.php(574): Tubee\Async\Sync->start()
#7 /usr/share/tubee/vendor/gyselroth/mongodb-php-task-scheduler/src/Worker.php(482): TaskScheduler\Worker->executeJob(Array)
#8 /usr/share/tubee/vendor/gyselroth/mongodb-php-task-scheduler/src/Worker.php(333): TaskScheduler\Worker->processJob(Array)
#9 /usr/share/tubee/vendor/gyselroth/mongodb-php-task-scheduler/src/Worker.php(227): TaskScheduler\Worker->queueJob(Array)
#10 /usr/share/tubee/vendor/gyselroth/mongodb-php-task-scheduler/src/WorkerManager.php(287): TaskScheduler\Worker->processAll()
#11 /usr/share/tubee/vendor/gyselroth/mongodb-php-task-scheduler/src/WorkerManager.php(473): TaskScheduler\WorkerManager->spawnWorker()
#12 /usr/share/tubee/vendor/gyselroth/mongodb-php-task-scheduler/src/WorkerManager.php(332): TaskScheduler\WorkerManager->handleJob(Array)
#13 /usr/share/tubee/vendor/gyselroth/mongodb-php-task-scheduler/src/WorkerManager.php(176): TaskScheduler\WorkerManager->main()
#14 /usr/share/tubee/vendor/gyselroth/mongodb-php-task-scheduler/src/Queue.php(148): TaskScheduler\WorkerManager->process()
#15 /usr/share/tubee/vendor/gyselroth/mongodb-php-task-scheduler/src/Queue.php(93): TaskScheduler\Queue->initWorkerManager()
#16 /usr/share/tubee/src/lib/Console/Jobs.php(69): TaskScheduler\Queue->process()
#17 /usr/share/tubee/src/lib/Bootstrap/Cli.php(106): Tubee\Console\Jobs->__invoke()
#18 /usr/share/tubee/src/lib/Bootstrap/Cli.php(130): Tubee\Bootstrap\Cli->executeCommand(Object(Tubee\Console\Jobs))
#19 /usr/share/tubee/src/lib/Bootstrap/Cli.php(91): Tubee\Bootstrap\Cli->routeCommand()
#20 /usr/share/tubee/bin/console/tubeecli(24): Tubee\Bootstrap\Cli->process()
#21 {main}
```

#### To Reproduce
Import from CsvEndpoint with a csv file without a headerline.
And workflow mappings to specific header names.

#### Environment
 - tubee server version: [e.g. v1.0.0]
 - tubectl version: [e.g. v1.0.0]
 - MongoDB Version: [e.g. v3.4.18]
 - PHP Version [e.g. v7.2.1]

**Comment by itsdarrylnorris** [comment]
Hey @raffis ,

I am running into the same issue. Did you ever got to the bottom of this problem?
